// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-swarmdrop-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SwarmdropCoreSpec.h"

@interface SwarmdropCore : NSObject <NativeSwarmdropCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SwarmdropCore : NSObject <RCTBridgeModule>
#endif

@end