// Generated by uniffi-bindgen-react-native
#include "react-native-swarmdrop-core.h"
#include "generated/swarmdrop_mobile_core.hpp"

namespace swarmdropcore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSwarmdropMobileCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}